import { Geist, Geist_Mono, Roboto_Flex } from "next/font/google";
import NavBar from "./components/common/NavBar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const robo = Roboto_Flex({
  subsets:["cyrillic"],
  weight:['100', '200','300','400','500','600','700','800','900'],
  variable:'--font-roboto'
})



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${robo.variable} antialiased bg-darker`}
      > 
      <NavBar/>
        {children}
      </body>
    </html>
  );
}
